apiVersion: apps/v1
kind: Deployment
metadata:
  name: mahiopsai-backend
  namespace: mahiopsai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mahiopsai-backend
  template:
    metadata:
      labels:
        app: mahiopsai-backend
    spec:
      containers:
        - name: backend
          image: mahiopsai-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: mahiopsai-backend-service
  namespace: mahiopsai
spec:
  selector:
    app: mahiopsai-backend
  ports:
    - port: 8000
      targetPort: 8000
  type: NodePort
